import js from '@eslint/js';

export default [
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: {
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        exports: 'readonly',
      },
    },
    plugins: {},
    rules: {
      ...js.configs.recommended.rules,
      'no-unused-vars': 'warn',
      'consistent-return': 'warn',
      'no-console': 'off',
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'warn',
      'no-empty': 'warn',
      'no-mixed-spaces-and-tabs': 'error',
      'no-unexpected-multiline': 'error',
      'no-duplicate-case': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-imports': 'warn',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-useless-catch': 'warn',
      'no-useless-return': 'warn',
      'require-await': 'warn',
      'no-return-await': 'warn',
      'no-async-promise-executor': 'warn',
      'no-prototype-builtins': 'warn',
      'no-case-declarations': 'warn',
      'no-shadow': 'warn',
      'no-fallthrough': 'warn',
      'no-else-return': 'warn',
      'no-lonely-if': 'warn',
      'no-irregular-whitespace': 'error',
      'no-multi-spaces': 'warn',
      'no-multiple-empty-lines': ['warn', { max: 2 }],
    },
  },
]; 